create or replace table GLOBALBANK.TRANSFORM_DATA.customer360 AS SELECT * FROM PC_DBT_DB.DBT_SDHADAM.CUSTOMER360;

create or replace table GLOBALBANK.TRANSFORM_DATA.customer_spending AS SELECT * FROM PC_DBT_DB.DBT_SDHADAM.CUSTOMER_SPENDING;

create or replace table GLOBALBANK.TRANSFORM_DATA.customer_accounts AS SELECT * FROM PC_DBT_DB.DBT_SDHADAM.CUSTOMER_ACCOUNTS;

